name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build
      - run: sudo snap install chromium
      - run: echo "CHROME_BIN=/snap/bin/chromium" >> .env
      - run: npm test -- --single-run
